# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyeccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivoespelcifico',
            name='informacion_descriptiva_id',
        ),
        migrations.AddField(
            model_name='informaciondescriptiva',
            name='objetivos_especificos',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='impacto',
            field=models.TextField(default='', null=True),
        ),
        migrations.DeleteModel(
            name='ObjetivoEspelcifico',
        ),
    ]
