# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyeccion', '0002_auto_20160930_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='justificacion',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='metodologia',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='objetivo_general',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='objetivos_especificos',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='poblacion',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='problema',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='titulo',
            field=models.CharField(max_length=400),
        ),
    ]
