# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyeccion', '0003_auto_20161001_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='impacto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='justificacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='metodologia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='objetivo_general',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='objetivos_especificos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='poblacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='informaciondescriptiva',
            name='problema',
            field=models.TextField(),
        ),
    ]
