# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyeccion', '0005_programa_proyecto_recursodocente_recursoestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoestudiante',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
